import Head from 'next/head'
//icons
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { BsSunFill } from 'react-icons/bs'
import { BsCircleFill } from 'react-icons/bs'
import { BsCircle } from 'react-icons/bs'
import { SiJavascript } from 'react-icons/si'
import { FaReact } from 'react-icons/fa'
import { BsCircleHalf } from 'react-icons/bs'
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from 'react-icons/ai'
import { AiFillHtml5 } from 'react-icons/ai'
import { DiCss3 } from 'react-icons/di'
//images
import Image from 'next/image';
import devsd from '../public/dev-ed-wave.png'
import web1 from '../public/movieland.png'
import web2 from '../public/weather-app.png'
import web3 from '../public/E-com.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  const [selectedIcon, setIcon] = useState(<BsFillMoonStarsFill className='text-gray-900 cursor-pointer text-2xl' />)
  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Saidahmad Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
          <section className='min-h-screen'>
            <nav className='pt-10 pb-2 mb-2 flex justify-between'>
              <h1 className='text-xl font-burtons dark:text-white'>by Saidahmad</h1>
              <ul className='flex items-center'>
                <li onClick={() => {
                  setDarkMode(() => !darkMode)
                  {
                    setIcon(darkMode ?
                      <BsFillMoonStarsFill className=' text-gray-900 cursor-pointer text-2xl' />
                      : <BsSunFill className='cursor-pointer dark:text-2xl dark:text-white' />)
                  }
                }}>
                  {selectedIcon}
                </li>
                <li>
                  <a href='https://drive.google.com/file/d/1FiIcLsFUYPQxoOqZYsOx_ToksAiaLinA/view?usp=share_link' target={'_blank'} download className='bg-gradient-to-r from-cyan-500 to-green-500 text-white py-2 px-4 rounded-md ml-8'>Get CV</a>
                </li>
              </ul>
            </nav>
            <div className=' text-center p-10'>
              <h2 className=' text-teal-600 py-2 text-5xl font-medium md:text-6xl'>Saidahmad</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Front-End Developer and Designer</h3>
              <p className='text-md py-5 text-gray-800 leading-8 md:text-xl max-w-xl mx-auto dark:text-white'>Freelancer providing services for programming and design content needs.
                Join me down below and let&apos;s get cracking!
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 text-gray-700 py-3 transition-transform dark:text-teal-600'>
              <a href='https://github.com/Saidahmadkhon001' target={'_blank'}> <AiFillGithub className='cursor-pointer' /> </a>
              <a href='https://www.linkedin.com/in/saidahmad-kholmuhammadkhonov-0a6931196/' target={'_blank'}> <AiFillLinkedin className='cursor-pointer' /> </a>
              <a href='https://instagram.com/Saidahmadkhon001' target={'_blank'}> <AiFillInstagram className='cursor-pointer' /> </a>
            </div>
            <div className='relative mx-auto mt-20 bg-gradient-to-b from-teal-500 rounded-full h-80 w-80 overflow-hidden'>
              <Image alt='' src={devsd} layout="fill" objectFit='cover' className='' />
            </div>
          </section>

          <section>
            <div className='text-center p-10'>
              <h3 className='text-3xl py-1 dark:text-white'>SKILLS</h3>
              <p className='text-md py-3 leading-8 text-gray-800 dark:text-white'> I have learned and am still learning a number
                Web Development programming tools and industry knowledge.
                They range from <span className='text-orange-500 font-md'>HTML/CSS </span>
                to advanced JavaScript frameworks like <span className='text-teal-500 font-md'>ReactJS</span></p>
              <p className='text-md py-3 leading-8 text-gray-800 dark:text-white'>Here you can what skills I have and how good I know them</p>
            </div>
            <div className='md:flex gap-10'>
              <div className='lg:w-1/3 md:w-1/3 text-center shadow-lg p-10 rounded-xl my-10 bg-orange-200 dark:bg-gray-800'>
                {/* <Image src={design} alt='' width={100} height={100} /> */}
                <div className='flex'>

                  <p className=' text-orange-500 mx-auto text-4xl font-semibold mb-5 mt-5'>HTML/CSS</p>
                </div>
                <h3 className='text-lg font-medium  pb-2 dark:text-orange-500'>HTML and CSS</h3>
                <div className='flex gap-1  justify-center mt-5'>
                  <BsCircleFill className='text-xl text-orange-500' />
                  <BsCircleFill className='text-xl text-orange-500' />
                  <BsCircleFill className='text-xl text-orange-500' />
                  <BsCircleFill className='text-xl text-orange-500' />
                  <BsCircle className='text-xl text-orange-500' />
                </div>
              </div>
              <div className='lg:w-1/3 md:w-1/3 text-center shadow-lg p-10 rounded-xl my-10 bg-yellow-200 dark:bg-gray-800'>
                {/* <Image alt='' src={design} width={100} height={100} /> */}
                <SiJavascript className='text-5xl mx-auto mt-5 mb-7 text-yellow-400' />
                <h3 className='text-lg font-medium pb-2 dark:text-yellow-400'>JavaScript</h3>
                <div className='flex gap-1  justify-center mt-5'>
                  <BsCircleFill className='text-xl text-yellow-400' />
                  <BsCircleFill className='text-xl text-yellow-400' />
                  <BsCircleFill className='text-xl text-yellow-400' />
                  <BsCircleHalf className='text-xl text-yellow-400' />
                  <BsCircle className='text-xl text-yellow-400' />
                </div>
              </div>
              <div className='lg:w-1/3 md:w-1/3 text-center shadow-lg p-10 rounded-xl my-10 bg-cyan-200 dark:bg-gray-800'>
                {/* <Image alt='' src={design} width={100} height={100} /> */}
                <FaReact className='text-5xl mx-auto mt-5 mb-7 text-cyan-500' />
                <h3 className='text-lg font-medium pb-2 dark:text-cyan-500'>ReactJS</h3>
                <div className='flex gap-1  justify-center mt-5'>
                  <BsCircleFill className='text-xl text-cyan-500' />
                  <BsCircleFill className='text-xl text-cyan-500' />
                  <BsCircleFill className='text-xl text-cyan-500' />
                  <BsCircle className='text-xl text-cyan-500' />
                  <BsCircle className='text-xl text-cyan-500' />
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className='text-center'>
              <h3 className='text-3xl py-1 dark:text-white'>Projects</h3>
              <p className='text-md py-3 leading-8 text-gray-800 dark:text-white'>Using what I have learned I was able to built and design
                a number outstanding websites and applications.
                They range from a simple <span className='text-teal-500 font-md'>ToDo List </span>
                to a fully working <span className='text-teal-500 font-md'>E-commerce Website</span></p>
            </div>

            {/* Projects  */}

            <div className='lg:flex gap-10 p-10 sm:flex-row'>

              {/* Project 1   */}

              <div className='shadow-lg p-5 mb-3 rounded-lg bg-slate-50 dark:bg-gray-800'>
                <Image src={web1} alt='' className='rounded-lg object-cover' />
                <h3 className='text-2xl my-3 font-medium text-center text-teal-500'>Movileand</h3>
                <p className='text-center dark:text-white'>Using React, HTML and CSS and a third-party API,
                  this beautiful app was built to search movies by name.
                </p>
                <p className='text-center my-3 text-xl font-normal text-teal-600'>Stack I used:</p>
                <div className='flex justify-between'>
                  <p className='text-orange-500 '>HTML</p>
                  <p className='text-blue-500'>CSS</p>
                  <p className='text-cyan-500'>ReactJS</p>
                  <p className='text-yellow-500'>API</p>
                </div>
                <div className='text-center'>
                  <button className='bg-gradient-to-r from-cyan-500 to-teal-600 text-white px-8 py-1 text-xl mt-4 rounded-lg font-normal'><a href="https://master--stupendous-mousse-3aa5b4.netlify.app/" target={'_blank'}>View Site</a></button>
                </div>
              </div>

              {/* Project 2 */}

              <div className='shadow-lg mb-3 p-5 rounded-lg bg-slate-50 dark:bg-gray-800'>
                <Image src={web2} alt='' className='rounded-lg object-cover' />
                <h3 className='text-2xl my-3 font-medium text-center text-purple-500'>Weather App</h3>
                <p className='text-center dark:text-white'>This app allows you to to see weather information
                  in different cities of the world. Give it a try by typing your city!
                </p>
                <p className='text-center my-3 text-xl font-normal text-teal-600'>Stack I used:</p>
                <div className='flex justify-between'>
                  <p className='text-orange-500 '>HTML</p>
                  <p className='text-pink-500'>CSS</p>
                  <p className='text-cyan-500'>JavaScript</p>
                  <p className='text-yellow-500'>API</p>
                </div>
                <div className='text-center'>
                  <button className='bg-gradient-to-r from-purple-500 to-teal-600 text-white px-8 py-1 text-xl mt-4 rounded-lg font-normal'><a href="https://master--classy-gecko-eef318.netlify.app/" target={"_blank"}>View Site</a></button>
                </div>
              </div>

              {/* Project 3 */}

              <div className='shadow-lg mb-3 p-5 rounded-lg bg-slate-50 dark:bg-gray-800'>
                <Image src={web3} alt='' className='rounded-lg object-cover' />
                <h3 className='text-2xl my-3 font-medium text-center text-teal-500'>E-Com Home Page</h3>
                <p className='text-center dark:text-white'>This project is the combination of HTML and mainly CSS.
                  JavaScript plays a big role on site functionality.
                </p>
                <p className='text-center my-3 text-xl font-normal text-teal-600'>Stack I used:</p>
                <div className='flex justify-between'>
                  <p className='text-orange-500 '>HTML</p>
                  <p className='text-blue-500'>CSS</p>
                  <p className='text-cyan-500'>ReactJS</p>
                  <p className='text-yellow-500'>API</p>
                </div>
                <div className='text-center'>
                  <button className='bg-gradient-to-r from-cyan-500 to-teal-600 text-white px-8 py-1 text-xl mt-4 rounded-lg font-normal'><a href="https://shiny-meerkat-b0b40e.netlify.app/index.html" target={'_blank'}>View Site</a></button>
                </div>
              </div>

            </div>

            <section className='relative'>
              <div className='lg:relative bg-slate-50 p-2 dark:bg-slate-800 rounded-md'>
                {/* <h3 className='text-teal-600 py-0 text-center text-3xl font-medium md:text-3xl'>Saidahmad Portfolio</h3> */}
                <div className=' lg:absolute left-10 py-3'>
                  <ul className='flex justify-center text-lg text-gray-700 gap-10 cursor-pointer dark:text-white'>
                    {/* <li><a href="#">Home</a></li> */}
                    <li><a href="mailto:saidahmadkhon001@gmail.com"><span className='text-cyan-500'>Email:</span> saidahmadkhon001@gmail</a></li>
                    <li><a href="tel:+48733806950"><span className='text-cyan-500'>Phone:</span>  +48 733 806 950</a></li>
                  </ul>
                </div>
                <div className='flex gap-10 justify-end text-3xl px-6  text-gray-700 py-3 transition-transform dark:text-teal-600'>
                  <a href='https://github.com/Saidahmadkhon001' target={'_blank'}> <AiFillGithub className='cursor-pointer' /> </a>
                  <a href='https://www.linkedin.com/in/saidahmad-kholmuhammadkhonov-0a6931196/' target={'_blank'}> <AiFillLinkedin className='cursor-pointer' /> </a>
                  <a href='https://instagram.com/Saidahmadkhon001' target={'_blank'}> <AiFillInstagram className='cursor-pointer' /> </a>
                </div>
                <p className='text-center pt-3 text-gray-700 dark:text-white'>&#169; 2023 Saidahmad Kholmuhammadkhonov</p>
              </div>
            </section> 
          </section>
        </main>
      </div>
    </>
  )
}
